#!/bin/bash
echo "Memulai setup Armbian..."
nano /etc/network/interfaces.d/*
# Network is managed by Network manager
auto eth0
iface eth0 inet dhcp

hwaddress ether 00:15:18:01:81:31
iface lo inet loopback
